#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOODMUSIC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLWedNhac")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBAI_HAT(BAI_HAT instance);
    partial void UpdateBAI_HAT(BAI_HAT instance);
    partial void DeleteBAI_HAT(BAI_HAT instance);
    partial void InsertCA_SI(CA_SI instance);
    partial void UpdateCA_SI(CA_SI instance);
    partial void DeleteCA_SI(CA_SI instance);
    partial void InsertCAU_HINH(CAU_HINH instance);
    partial void UpdateCAU_HINH(CAU_HINH instance);
    partial void DeleteCAU_HINH(CAU_HINH instance);
    partial void InsertCHU_DE(CHU_DE instance);
    partial void UpdateCHU_DE(CHU_DE instance);
    partial void DeleteCHU_DE(CHU_DE instance);
    partial void InsertMV(MV instance);
    partial void UpdateMV(MV instance);
    partial void DeleteMV(MV instance);
    partial void InsertTOP_20(TOP_20 instance);
    partial void UpdateTOP_20(TOP_20 instance);
    partial void DeleteTOP_20(TOP_20 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLWedNhacConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BAI_HAT> BAI_HATs
		{
			get
			{
				return this.GetTable<BAI_HAT>();
			}
		}
		
		public System.Data.Linq.Table<CA_SI> CA_SIs
		{
			get
			{
				return this.GetTable<CA_SI>();
			}
		}
		
		public System.Data.Linq.Table<CAU_HINH> CAU_HINHs
		{
			get
			{
				return this.GetTable<CAU_HINH>();
			}
		}
		
		public System.Data.Linq.Table<CHU_DE> CHU_DEs
		{
			get
			{
				return this.GetTable<CHU_DE>();
			}
		}
		
		public System.Data.Linq.Table<MV> MVs
		{
			get
			{
				return this.GetTable<MV>();
			}
		}
		
		public System.Data.Linq.Table<TOP_20> TOP_20s
		{
			get
			{
				return this.GetTable<TOP_20>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAI_HAT")]
	public partial class BAI_HAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBH;
		
		private int _IDCS;
		
		private string _TENBH;
		
		private int _THUTU;
		
		private string _ANH;
		
		private string _LINK;
		
		private string _CASI;
		
		private EntityRef<CA_SI> _CA_SI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBHChanging(int value);
    partial void OnIDBHChanged();
    partial void OnIDCSChanging(int value);
    partial void OnIDCSChanged();
    partial void OnTENBHChanging(string value);
    partial void OnTENBHChanged();
    partial void OnTHUTUChanging(int value);
    partial void OnTHUTUChanged();
    partial void OnANHChanging(string value);
    partial void OnANHChanged();
    partial void OnLINKChanging(string value);
    partial void OnLINKChanged();
    partial void OnCASIChanging(string value);
    partial void OnCASIChanged();
    #endregion
		
		public BAI_HAT()
		{
			this._CA_SI = default(EntityRef<CA_SI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDBH
		{
			get
			{
				return this._IDBH;
			}
			set
			{
				if ((this._IDBH != value))
				{
					this.OnIDBHChanging(value);
					this.SendPropertyChanging();
					this._IDBH = value;
					this.SendPropertyChanged("IDBH");
					this.OnIDBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCS", DbType="Int NOT NULL")]
		public int IDCS
		{
			get
			{
				return this._IDCS;
			}
			set
			{
				if ((this._IDCS != value))
				{
					if (this._CA_SI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDCSChanging(value);
					this.SendPropertyChanging();
					this._IDCS = value;
					this.SendPropertyChanged("IDCS");
					this.OnIDCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBH", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENBH
		{
			get
			{
				return this._TENBH;
			}
			set
			{
				if ((this._TENBH != value))
				{
					this.OnTENBHChanging(value);
					this.SendPropertyChanging();
					this._TENBH = value;
					this.SendPropertyChanged("TENBH");
					this.OnTENBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THUTU", DbType="Int NOT NULL")]
		public int THUTU
		{
			get
			{
				return this._THUTU;
			}
			set
			{
				if ((this._THUTU != value))
				{
					this.OnTHUTUChanging(value);
					this.SendPropertyChanging();
					this._THUTU = value;
					this.SendPropertyChanged("THUTU");
					this.OnTHUTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANH", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ANH
		{
			get
			{
				return this._ANH;
			}
			set
			{
				if ((this._ANH != value))
				{
					this.OnANHChanging(value);
					this.SendPropertyChanging();
					this._ANH = value;
					this.SendPropertyChanged("ANH");
					this.OnANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINK", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string LINK
		{
			get
			{
				return this._LINK;
			}
			set
			{
				if ((this._LINK != value))
				{
					this.OnLINKChanging(value);
					this.SendPropertyChanging();
					this._LINK = value;
					this.SendPropertyChanged("LINK");
					this.OnLINKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CASI
		{
			get
			{
				return this._CASI;
			}
			set
			{
				if ((this._CASI != value))
				{
					this.OnCASIChanging(value);
					this.SendPropertyChanging();
					this._CASI = value;
					this.SendPropertyChanged("CASI");
					this.OnCASIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CA_SI_BAI_HAT", Storage="_CA_SI", ThisKey="IDCS", OtherKey="IDCS", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CA_SI CA_SI
		{
			get
			{
				return this._CA_SI.Entity;
			}
			set
			{
				CA_SI previousValue = this._CA_SI.Entity;
				if (((previousValue != value) 
							|| (this._CA_SI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CA_SI.Entity = null;
						previousValue.BAI_HATs.Remove(this);
					}
					this._CA_SI.Entity = value;
					if ((value != null))
					{
						value.BAI_HATs.Add(this);
						this._IDCS = value.IDCS;
					}
					else
					{
						this._IDCS = default(int);
					}
					this.SendPropertyChanged("CA_SI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CA_SI")]
	public partial class CA_SI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCS;
		
		private string _HOTEN;
		
		private EntitySet<BAI_HAT> _BAI_HATs;
		
		private EntitySet<MV> _MVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCSChanging(int value);
    partial void OnIDCSChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    #endregion
		
		public CA_SI()
		{
			this._BAI_HATs = new EntitySet<BAI_HAT>(new Action<BAI_HAT>(this.attach_BAI_HATs), new Action<BAI_HAT>(this.detach_BAI_HATs));
			this._MVs = new EntitySet<MV>(new Action<MV>(this.attach_MVs), new Action<MV>(this.detach_MVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDCS
		{
			get
			{
				return this._IDCS;
			}
			set
			{
				if ((this._IDCS != value))
				{
					this.OnIDCSChanging(value);
					this.SendPropertyChanging();
					this._IDCS = value;
					this.SendPropertyChanged("IDCS");
					this.OnIDCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CA_SI_BAI_HAT", Storage="_BAI_HATs", ThisKey="IDCS", OtherKey="IDCS")]
		public EntitySet<BAI_HAT> BAI_HATs
		{
			get
			{
				return this._BAI_HATs;
			}
			set
			{
				this._BAI_HATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CA_SI_MV", Storage="_MVs", ThisKey="IDCS", OtherKey="IDCS")]
		public EntitySet<MV> MVs
		{
			get
			{
				return this._MVs;
			}
			set
			{
				this._MVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BAI_HATs(BAI_HAT entity)
		{
			this.SendPropertyChanging();
			entity.CA_SI = this;
		}
		
		private void detach_BAI_HATs(BAI_HAT entity)
		{
			this.SendPropertyChanging();
			entity.CA_SI = null;
		}
		
		private void attach_MVs(MV entity)
		{
			this.SendPropertyChanging();
			entity.CA_SI = this;
		}
		
		private void detach_MVs(MV entity)
		{
			this.SendPropertyChanging();
			entity.CA_SI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAU_HINH")]
	public partial class CAU_HINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCH;
		
		private string _GIATRI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCHChanging(int value);
    partial void OnIDCHChanged();
    partial void OnGIATRIChanging(string value);
    partial void OnGIATRIChanged();
    #endregion
		
		public CAU_HINH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDCH
		{
			get
			{
				return this._IDCH;
			}
			set
			{
				if ((this._IDCH != value))
				{
					this.OnIDCHChanging(value);
					this.SendPropertyChanging();
					this._IDCH = value;
					this.SendPropertyChanged("IDCH");
					this.OnIDCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIATRI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string GIATRI
		{
			get
			{
				return this._GIATRI;
			}
			set
			{
				if ((this._GIATRI != value))
				{
					this.OnGIATRIChanging(value);
					this.SendPropertyChanging();
					this._GIATRI = value;
					this.SendPropertyChanged("GIATRI");
					this.OnGIATRIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHU_DE")]
	public partial class CHU_DE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCD;
		
		private string _HINHCD;
		
		private string _TENCD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCDChanging(int value);
    partial void OnIDCDChanged();
    partial void OnHINHCDChanging(string value);
    partial void OnHINHCDChanged();
    partial void OnTENCDChanging(string value);
    partial void OnTENCDChanged();
    #endregion
		
		public CHU_DE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDCD
		{
			get
			{
				return this._IDCD;
			}
			set
			{
				if ((this._IDCD != value))
				{
					this.OnIDCDChanging(value);
					this.SendPropertyChanging();
					this._IDCD = value;
					this.SendPropertyChanged("IDCD");
					this.OnIDCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHCD", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string HINHCD
		{
			get
			{
				return this._HINHCD;
			}
			set
			{
				if ((this._HINHCD != value))
				{
					this.OnHINHCDChanging(value);
					this.SendPropertyChanging();
					this._HINHCD = value;
					this.SendPropertyChanged("HINHCD");
					this.OnHINHCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCD", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENCD
		{
			get
			{
				return this._TENCD;
			}
			set
			{
				if ((this._TENCD != value))
				{
					this.OnTENCDChanging(value);
					this.SendPropertyChanging();
					this._TENCD = value;
					this.SendPropertyChanged("TENCD");
					this.OnTENCDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MV")]
	public partial class MV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDMV;
		
		private int _IDCS;
		
		private string _TENMV;
		
		private System.DateTime _NGAYCAPNHAT;
		
		private int _THUTU;
		
		private string _LINK;
		
		private string _ANH;
		
		private string _CASI;
		
		private EntityRef<CA_SI> _CA_SI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMVChanging(int value);
    partial void OnIDMVChanged();
    partial void OnIDCSChanging(int value);
    partial void OnIDCSChanged();
    partial void OnTENMVChanging(string value);
    partial void OnTENMVChanged();
    partial void OnNGAYCAPNHATChanging(System.DateTime value);
    partial void OnNGAYCAPNHATChanged();
    partial void OnTHUTUChanging(int value);
    partial void OnTHUTUChanged();
    partial void OnLINKChanging(string value);
    partial void OnLINKChanged();
    partial void OnANHChanging(string value);
    partial void OnANHChanged();
    partial void OnCASIChanging(string value);
    partial void OnCASIChanged();
    #endregion
		
		public MV()
		{
			this._CA_SI = default(EntityRef<CA_SI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDMV
		{
			get
			{
				return this._IDMV;
			}
			set
			{
				if ((this._IDMV != value))
				{
					this.OnIDMVChanging(value);
					this.SendPropertyChanging();
					this._IDMV = value;
					this.SendPropertyChanged("IDMV");
					this.OnIDMVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCS", DbType="Int NOT NULL")]
		public int IDCS
		{
			get
			{
				return this._IDCS;
			}
			set
			{
				if ((this._IDCS != value))
				{
					if (this._CA_SI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDCSChanging(value);
					this.SendPropertyChanging();
					this._IDCS = value;
					this.SendPropertyChanged("IDCS");
					this.OnIDCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMV", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENMV
		{
			get
			{
				return this._TENMV;
			}
			set
			{
				if ((this._TENMV != value))
				{
					this.OnTENMVChanging(value);
					this.SendPropertyChanging();
					this._TENMV = value;
					this.SendPropertyChanged("TENMV");
					this.OnTENMVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCAPNHAT", DbType="Date NOT NULL")]
		public System.DateTime NGAYCAPNHAT
		{
			get
			{
				return this._NGAYCAPNHAT;
			}
			set
			{
				if ((this._NGAYCAPNHAT != value))
				{
					this.OnNGAYCAPNHATChanging(value);
					this.SendPropertyChanging();
					this._NGAYCAPNHAT = value;
					this.SendPropertyChanged("NGAYCAPNHAT");
					this.OnNGAYCAPNHATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THUTU", DbType="Int NOT NULL")]
		public int THUTU
		{
			get
			{
				return this._THUTU;
			}
			set
			{
				if ((this._THUTU != value))
				{
					this.OnTHUTUChanging(value);
					this.SendPropertyChanging();
					this._THUTU = value;
					this.SendPropertyChanged("THUTU");
					this.OnTHUTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINK", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string LINK
		{
			get
			{
				return this._LINK;
			}
			set
			{
				if ((this._LINK != value))
				{
					this.OnLINKChanging(value);
					this.SendPropertyChanging();
					this._LINK = value;
					this.SendPropertyChanged("LINK");
					this.OnLINKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANH", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ANH
		{
			get
			{
				return this._ANH;
			}
			set
			{
				if ((this._ANH != value))
				{
					this.OnANHChanging(value);
					this.SendPropertyChanging();
					this._ANH = value;
					this.SendPropertyChanged("ANH");
					this.OnANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASI", DbType="NVarChar(200)")]
		public string CASI
		{
			get
			{
				return this._CASI;
			}
			set
			{
				if ((this._CASI != value))
				{
					this.OnCASIChanging(value);
					this.SendPropertyChanging();
					this._CASI = value;
					this.SendPropertyChanged("CASI");
					this.OnCASIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CA_SI_MV", Storage="_CA_SI", ThisKey="IDCS", OtherKey="IDCS", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CA_SI CA_SI
		{
			get
			{
				return this._CA_SI.Entity;
			}
			set
			{
				CA_SI previousValue = this._CA_SI.Entity;
				if (((previousValue != value) 
							|| (this._CA_SI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CA_SI.Entity = null;
						previousValue.MVs.Remove(this);
					}
					this._CA_SI.Entity = value;
					if ((value != null))
					{
						value.MVs.Add(this);
						this._IDCS = value.IDCS;
					}
					else
					{
						this._IDCS = default(int);
					}
					this.SendPropertyChanged("CA_SI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOP_20")]
	public partial class TOP_20 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTOP;
		
		private string _HINHTOP;
		
		private string _TENTOP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTOPChanging(int value);
    partial void OnIDTOPChanged();
    partial void OnHINHTOPChanging(string value);
    partial void OnHINHTOPChanged();
    partial void OnTENTOPChanging(string value);
    partial void OnTENTOPChanged();
    #endregion
		
		public TOP_20()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTOP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTOP
		{
			get
			{
				return this._IDTOP;
			}
			set
			{
				if ((this._IDTOP != value))
				{
					this.OnIDTOPChanging(value);
					this.SendPropertyChanging();
					this._IDTOP = value;
					this.SendPropertyChanged("IDTOP");
					this.OnIDTOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHTOP", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string HINHTOP
		{
			get
			{
				return this._HINHTOP;
			}
			set
			{
				if ((this._HINHTOP != value))
				{
					this.OnHINHTOPChanging(value);
					this.SendPropertyChanging();
					this._HINHTOP = value;
					this.SendPropertyChanged("HINHTOP");
					this.OnHINHTOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTOP", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENTOP
		{
			get
			{
				return this._TENTOP;
			}
			set
			{
				if ((this._TENTOP != value))
				{
					this.OnTENTOPChanging(value);
					this.SendPropertyChanging();
					this._TENTOP = value;
					this.SendPropertyChanged("TENTOP");
					this.OnTENTOPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
